spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eom
      #uri: mongodb://user:${MONGODB_PASSWORD}@localhost:25000
      port: 27017

server:
  context-path: /uaa
  port: 5000
  use-forward-headers: false

ldap:
  contextSource:
    url: ldaps://ldap.vn.exadel.com:636
    userDn: cn=LDAPaccess,ou=Special,dc=exadel,dc=com
    password: ${LDAP_PASSWORD}
  search:
    userSearchBase: ou=addressbook,dc=exadel,dc=com
    userSearchFilter: (uid={0})
    groupSearchBase: ou=Groups,dc=exadel,dc=com
    groupSearchFilter: (member={1})
    groupRoleAttribute: cn