spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eom
      port: 27017

server:
  context-path: /uaa
  port: 5000

ldap:
  contextSource:
    url: ldap://localhost:389
    base: cn=Users,dc=test,dc=local
    userDn: uid={0},ou=people
    password: testPass
  search:
    userDnPatterns: uid={0},ou=people
    groupSearchBase: ou=groups