spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eom
      port: 27017

server:
  context-path: /uaa
  port: 5000

ldap:
  contextSource:
    url: ldaps://ldap.vn.exadel.com:636
    base: ou=addressbook,dc=exadel,dc=com
    userDn: cn=LDAPaccess,ou=Special,dc=exadel,dc=com
    password: ${LDAP_PASSWORD}
  search:
    userDnPatterns: (uid={0})
    groupSearchBase: ou=addressbook