management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: '*'
      cors:
        allowed-origins: true
    jmx:
      exposure:
        include: '*'
