security:
  oauth2:
    client:
      clientId: officemap-service
      clientSecret: ${OFFICEMAP_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: officemap-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eom
      port: 27017

server:
  context-path: /officemap
  port: 6000
